/* eslint-disable  @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { Onest } from 'next/font/google'
import { notFound } from 'next/navigation'

import SmoothScroll from '@/components/providers/SmoothScroll'

import { routing } from '@/i18n/routing'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const onest = Onest({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
	display: 'swap'
})

export function generateStaticParams() {
	return routing.locales.map(locale => ({ locale }))
}

export default async function RootLayout({
	children,
	params
}: {
	children: React.ReactNode
	params: Promise<{ locale: string }>
}) {
	const { locale } = await params
	if (!routing.locales.includes(locale as any)) {
		notFound()
	}

	// Enable static rendering
	setRequestLocale(locale)

	const messages = await getMessages()

	return (
		<html lang={locale}>
			<body className={`relative ${onest.className} bg-white`}>
				<NextIntlClientProvider messages={messages}>
					<SmoothScroll>{children}</SmoothScroll>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
