/* eslint-disable  @typescript-eslint/no-explicit-any */

import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Onest } from "next/font/google";
import "./globals.css";
import { getMessages, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import TrpcProvider from "../_trpc/TrpcProvider";
import SmoothScroll from "../components/providers/SmoothScroll";
import NavBar from "../components/NavBar/NavBar";
import Footer from "../components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const onest = Onest({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`relative ${onest.className}`}>
        <NextIntlClientProvider messages={messages}>
          <TrpcProvider>
            <SmoothScroll>
              <NavBar />
              {children}
              <Footer />
            </SmoothScroll>
          </TrpcProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
